### ISSUE TITLE
Automatically zip releases through Travis CI

### ISSUE THREAD

**Issue by voxpelli** [aaronpk/ca3db-node#1]
Just putting this one here as it's something I've been planning to do myself for my Lambda scripts – have Travis CI build them into a zip that's attached to a GitHub release: http://docs.travis-ci.com/user/deployment/releases/

Right now I, like you, document this in the Readme instead, but I find that documenting things in code is in most cases preferable as that leaves no room for misinterpretation about what to do.

**Comment by aaronpk** [comment]
Thanks for the tip. I'm going to close this because I've deprecated this project due to Amazon upgrading their Node.js version and this didn't port over seamlessly. I've since rewritten it in Ruby.
